version: "2"

services:
  app:
    build: .
    ports:
      - "8080"
    volumes:
      - ./uploads:/uploads
    working_dir: /
    environment:
      - VIRTUAL_HOST=razbox.xyz
      - VIRTUAL_PORT=8080
    command: -root /uploads -redis redis://redis:6379

  redis:
    image: redis:alpine
